main: com.superiorcraft.SuperiorCraft
name: SuperiorCraft
version: 3.4.2
author: SuperiorCraft Development (Auguste Rame)
description: SuperiorCraft is a server and an API. Learn more at https://www.github.com/GigaGamma/SuperiorCraft.
commands:
  cchat:
    description: Server Announcment's made Colorful
    usage: /cchat message
    permission: superiorcraft.cchat
    permission-message: You don't have the superiorcraft.cchat permission.
  nick:
    description: Who's nick?
    usage: /nick <name>
    permission: superiorcraft.nick
    permission-message: You don't have the superiorcraft.nick permission.
  fly:
    description: Take Flight
    usage: /fly
    permission: superiorcraft.fly
    permission-message: You don't have the superiorcraft.fly permission.
  heal:
    description: Regain health
    usage: /heal
    permission: superiorcraft.heal
    permission-message: You don't have the superiorcraft.heal permission.
  eat:
    description: Regain hunger points
    usage: /eat
    permission: superiorcraft.eat
    permission-message: You don't have the superiorcraft.eat permission.
  healthy:
    description: Regain hunger and health points
    usage: /healthy
    permission: superiorcraft.healthy
    permission-message: You don't have the superiorcraft.healthy permission.
  warp:
    description: Create and go to waypoints
    usage: /warp <add:remove:Waypoint name> [...]
  cloak:
    description: Cloak yourself
    usage: /cloak
    permission: superiorcraft.cloak
    permission-message: You don't have the superiorcraft.cloak permission.
  uncloak:
    description: Uncloak another player
    usage: /uncloak <player>
    permission: superiorcraft.uncloak
    permission-message: You don't have the superiorcraft.uncloak permission.
  list:
    description: List all players
    usage: /list
    permission: superiorcraft.list
    permission-message: You don't have the superiorcraft.list permission.
  docommand:
    description: Do command
    usage: /docommand <player> <command>
    permission: superiorcraft.docommand
    permission-message: You don't have the superiorcraft.docommand permission.
  invsee:
    description: See players inventory
    usage: /invsee <player>
    permission: superiorcraft.invsee
    permission-message: You don't have the superiorcraft.invsee permission.
  mute:
    description: Mute player
    usage: /mute <player>
    permission: superiorcraft.mute
    permission-message: You don't have the superiorcraft.mute permission.
  unmute:
    description: Unmute player
    usage: /unmute <player>
    permission: superiorcraft.unmute
    permission-message: You don't have the superiorcraft.unmute permission.
  mutelist:
    description: Mute list
    usage: /mutelist
    permission: superiorcraft.mutelist
    permission-message: You don't have the superiorcraft.mutelist permission.
  holo:
    description: Holograms
    usage: /holo
    permission: superiorcraft.holo
    permission-message: You don't have the superiorcraft.holo permission.
  kit:
    description: Kit
    usage: /kit
  worlds:
    description: Worlds
    usage: /worlds <add:remove:goto> [...]
    permission: superiorcraft.worlds
    permission-message: You don't have the superiorcraft.worlds permission.
  game:
    description: Game Controller
    usage: /game <join:leave> [...]
    permission: superiorcraft.game
    permission-message: You don't have the superiorcraft.game permission.
  rank:
    description: Rank Controller
    usage: /rank <player> <ranktype> <rank>
    permission: superiorcraft.rank
    permission-message: You don't have the superiorcraft.rank permission.
  myml:
    description: MenuYML
    usage: /myml <[file]:edit:reload> [...]
    permission: superiorcraft.myml
    permission-message: You don't have the superiorcraft.myml permission.
  hbike:
    description: hbike
    usage: /hbike
    permission: superiorcraft.hbike
    permission-message: You don't have the superiorcraft.hbike permission.
  getitem:
    description: getitem
    usage: /getitem
    permission: superiorcraft.getitem
    permission-message: You don't have the superiorcraft.getitem permission.
  getblock:
    description: getblock
    usage: /getblock
    permission: superiorcraft.getblock
    permission-message: You don't have the superiorcraft.getblock permission.
  velo:
    description: Velocity
    usage: /velo
    permission: superiorcraft.velo
    permission-message: You don't have the superiorcraft.velo permission.
  cp:
    description: To the flag!
    usage: /cp
  echest:
    description: Ender Chest
    usage: /echest
    permission: superiorcraft.echest
    permission-message: You don't have the superiorcraft.echest permission.
  gui:
    description: GUI
    usage: /gui [display:...]
    permission: superiorcraft.gui
    permission-message: You don't have the superiorcraft.gui permission.
  addmin:
    description: Admin control made simple
    usage: /addmin
    permission: superiorcraft.addmin
    permission-message: You don't have the superiorcraft.addmin permission.
  police:
    description: That's the sign of da police
    usage: /police
    permission: superiorcraft.police
    permission-message: You don't have the superiorcraft.police permission.
  camera:
    description: Watch
    usage: /camera
    permission: superiorcraft.security
    permission-message: Only the worthy unlock this prestigious command.
  spy:
    description: Stalk your friends
    usage: /spy
    permission: superiorcraft.spy
    permission-message: Don't spy
  mg:
    description: Minigames
    usage: /mg